name: Test project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.13, 3.14]

    steps:
      - name: Skip duplicate actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

      - name: Checkout code
        if: steps.skip_check.outputs.should_skip != 'true'
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        if: steps.skip_check.outputs.should_skip != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        if: steps.skip_check.outputs.should_skip != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        if: steps.skip_check.outputs.should_skip != 'true'
        run: pytest tests/ -v
